.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH goobook 1 "June 3, 2015" "" "goobook"
.SH NAME
goobook \- access your Google contacts from mutt or the command line

.SH SYNOPSIS
.B goobook
.RI [ options ]
.RI COMMAND
.br

.SH DESCRIPTION
.B goobook
can be used to access your Google contacts from the command line. It can also
be easily integrated into MUAs such as mutt. It can be used from mutt the same
way as abook.

.SH OPTIONS
.TP
\-h, \-\-help
show the help message and exit
.TP
\-c FILE, \-\-config FILE
specify alternative configuration file
.TP
\-v, \-\-verbose
be verbose about what is going on (stderr)
.TP
\-V, \-\-version
print version and exit
.TP
\-d, \-\-debug
output debug information to stderr

.SH COMMAND
.TP
authenticate
allow \fBgoobook\fR to access your Google contacts using OAuth2
.TP
add
read an email address from stdin and add the From: address to your Google
contacts
.TP
config-template
create a config template of
.B ~/.goobookrc
.TP
dump_contacts
dump all your contacts to XML (stdout)
.TP
dump_groups
dump your contact groups to XML (stdout)
.TP
dquery QUERY_STRING
search contacts for QUERY_STRING, nice vcard like output
.TP
query QUERY_STRING
search contacts for QUERY_STRING, plain text output
.TP
reload
reload contacts from Google and update cache

.SH CONFIGURATION
For most users it will be enough to run:

.nf
    \fBgoobook\fR authenticate
.fi
.PP
To have access to more advanced options, you can generate a config file by
doing:

.nf
    \fBgoobook\fR config-template > ~/.goobookrc
.fi
.PP
An example config can look like this:

.nf
    [DEFAULT]
    oauth_db_filename: ~/.goobook_auth.json
    cache_filename: ~/.goobook_cache
    cache_expiry_hours: 24
.fi

.SH "SEE ALSO
Website: https://pypi.python.org/pypi/goobook/

.SH AUTHOR

This manual page has been written by Dariusz Dwornikowski
<dariusz.dwornikowski@cs.put.poznan.pl>
